steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/ollama/ollama:latest || exit 0
  - name: gcr.io/cloud-builders/docker
    args: [
            'build', 
            '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama:${SHORT_SHA}', 
            '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama:${BRANCH_NAME}', 
            '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama:latest', 
            '--cache-from', 'gcr.io/$PROJECT_ID/ollama/ollama:latest',
            '--build-arg', 'COMMIT_SHA=${SHORT_SHA}', '--build-arg', 'BRANCH_NAME=${BRANCH_NAME}', '.']
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'BUILDKIT_INLINE_CACHE=1'

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama"]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "-a", "us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama"]
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run', 'deploy', 'ollama-try', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama:$SHORT_SHA', 
            '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated',
            '--concurrency', '4', '--cpu', '8', '--memory', '32Gi', '--set-env-vars', 'OLLAMA_NUM_PARALLEL=4',
            '--gpu', '1', '--gpu-type', 'nvidia-l4', '--max-instances', '7', '--min-instances', '0',
            '--no-cpu-throttling', '--timeout=600'
           ]
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/ollama/ollama
options:
  logging: CLOUD_LOGGING_ONLY
